version: '3.9'

services:
  web:
    build: .
    command: gunicorn student_project.wsgi:application --bind 0.0.0.0:8000 --workers 3 --threads 2 --timeout 30
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DJANGO_DEBUG: "False"
      POSTGRES_DB: django_db
      POSTGRES_USER: django_user
      POSTGRES_PASSWORD: django_password
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: django_db
      POSTGRES_USER: django_user
      POSTGRES_PASSWORD: django_password

volumes:
  postgres_data:
